name: Build on Windows with MSVC

on:
  push:
    branches:
    - '*'
    paths:
    - .github/workflows/build-windows-msvc.yml
    - build/CMakeLists.txt
    - build/cmake_modules/**
    - daemon/**
    - i18n/**
    - libi2pd/**
    - libi2pd_client/**
    - Win32/**
    tags:
    - '*'
  pull_request:
    branches:
    - '*'

jobs:
  build:
    name: Build
    runs-on: windows-latest

    strategy:
      fail-fast: false

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Build and install zlib
      run: |
        powershell -Command "(Invoke-WebRequest -Uri https://raw.githubusercontent.com/r4sas/zlib.install/master/install.bat -OutFile install_zlib.bat)"
        powershell -Command "(Get-Content install_zlib.bat) | Set-Content install_zlib.bat" # fixing line endings
        set BUILD_TYPE=Debug
        ./install_zlib.bat
        set BUILD_TYPE=Release
        ./install_zlib.bat
        del install_zlib.bat

    - name: Install Boost
      run: |
        powershell -Command "(Invoke-WebRequest -UserAgent "Wget" -Uri https://sourceforge.net/projects/boost/files/boost-binaries/1.81.0/boost_1_81_0-msvc-14.3-64.exe/download -OutFile boost_1_81_0-msvc-14.3-64.exe)"
        ./boost_1_81_0-msvc-14.3-64.exe /VERYSILENT

    #- name: Install OpenSSL
    #  run: |
    #    powershell -Command "(Invoke-WebRequest -UserAgent "Wget" -Uri https://slproweb.com/download/Win64OpenSSL-3_2_1.exe -OutFile Win64OpenSSL-3_2_1.exe)"
    #    ./Win64OpenSSL-3_2_1.exe /VERYSILENT /SUPPRESSMSGBOXES /NORESTART /SP-

    # Windows image already has OpenSSL installed to %programfiles%\OpenSSL, so we using that path, not OpenSSL-Win64
    #- name: Make copy of the OpenSSL libraries for CMake
    #  run: xcopy /y "c:\Program Files\OpenSSL\lib\VC\x64\MTd\*" "c:\Program Files\OpenSSL\lib\"

    - name: Configure
      working-directory: build
      run: cmake -DBoost_ROOT="C:\local\boost_1_81_0" -DWITH_STATIC=ON .

    - name: Build
      working-directory: build
      run: cmake --build . --config Debug -- -m

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: i2pd-msvc
        path: build/Debug/i2pd.*

